version: '3.8'

services:
  frontend:
    image: ${DOCKER_USER}/${PROJECT_NAME}-frontend:${IMAGE_TAG}
    build: 
      context: ./frontend
    ports:
      - "3000:80"
    networks: 
      - frontend
      - backend
  
  backend:
    image: ${DOCKER_USER}/${PROJECT_NAME}-backend:${IMAGE_TAG}
    build:
      context: ./backend
    networks: 
      - backend

networks: 
  frontend:
  backend: